const mongoose = require('mongoose');

const pokemonSchema = new mongoose.Schema({
    Name: String,
    Type1: String,
    Type2: String,
    Species: String,
    Height: String,
    Weight : String,
    Location: String,
    SW_Desc: String,
    SH_Desc: String,
    Ability_1: String,
    Ability_2: String,
    Hidden_Ability: String,
    Galar_Ability_1: String,
    Galar_Ability_2: String,
    Galar_Hidden_Ability: String,
    Alola_Ability_1: String,
    Alola_Ability_2: String,
    Alola_Hidden_Ability: String,
    HP: String,
    Attack: String,
    Defense: String,
    Special_Attack: String,
    Special_Defense: String,
    Speed: String,
    HP_Min: String,
    Attack_Min: String,
    Defense_Min: String,
    Special_Attack_Min: String,
    Special_Defense_Min: String,
    Speed_Min: String,
    HP_Max: String,
    Attack_Max: String,
    Defense_Max: String,
    Special_Attack_Max: String,
    Special_Defense_Max: String,
    Speed_Max: String,
    Normal_Weakness: String,
    Fire_Weakness: String,
    Water_Weakness: String,
    Electric_Weakness: String,
    Grass_Weakness: String,
    Ice_Weakness: String,
    Fighting_Weakness: String,
    Poison_Weakness: String,
    Ground_Weakness: String,
    Flying_Weakness: String,
    Psychic_Weakness: String,
    Bug_Weakness: String,
    Rock_Weakness: String,
    Ghost_Weakness: String,
    Dragon_Weakness: String,
    Dark_Weakness: String,
    Steel_Weakness: String,
    Fairy_Weakness: String
});

module.exports = mongoose.model('Pokemon', pokemonSchema);